/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Alejandro
 */
public class Agente extends javax.swing.JFrame {

    void limpiar() {

        TFnombre.setText("");
        TFid.setText("");
        SPNedad.setValue(0);

    }

    void actualizar() {
        Conexion cc = new Conexion();
        Connection cn = cc.conexion();
        String sql;
        ResultSet res;
        sql = "SELECT * FROM agente";
        try {

            PreparedStatement psd = cn.prepareStatement(sql);
            res = psd.executeQuery();
            cmbAGENTE2.removeAllItems();
            
            while (res.next()) {
                cmbAGENTE2.addItem(res.getString("DOCUMENTO_AGENT"));
               
            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex);

        }
    }

    public Agente() {
        initComponents();
        actualizar();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmenu = new javax.swing.JButton();
        TFnombre = new javax.swing.JTextField();
        LBLtitulo2 = new javax.swing.JLabel();
        LBLnombre = new javax.swing.JLabel();
        TFid = new javax.swing.JTextField();
        LBLid = new javax.swing.JLabel();
        LBLedad = new javax.swing.JLabel();
        SPNedad = new javax.swing.JSpinner();
        LBLgenero = new javax.swing.JLabel();
        CMBgenero = new javax.swing.JComboBox<>();
        BTNgrabar = new javax.swing.JButton();
        LBLtitulo1 = new javax.swing.JLabel();
        cmbAGENTE2 = new javax.swing.JComboBox<>();
        BTNconsultar = new javax.swing.JButton();
        BTNborrar = new javax.swing.JButton();
        BTNactualizar = new javax.swing.JButton();
        LBLnombre2 = new javax.swing.JLabel();
        LBLfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGENTES");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmenu.setText("MENU");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        TFnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnombreActionPerformed(evt);
            }
        });
        getContentPane().add(TFnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 150, -1));

        LBLtitulo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LBLtitulo2.setForeground(new java.awt.Color(255, 0, 51));
        LBLtitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLtitulo2.setText("CONSULTAR/BORRAR");
        getContentPane().add(LBLtitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 460, -1));

        LBLnombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBLnombre.setText("NOMBRE COMPLETO");
        getContentPane().add(LBLnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 20));
        getContentPane().add(TFid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 110, -1));

        LBLid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBLid.setText("ID");
        getContentPane().add(LBLid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        LBLedad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBLedad.setText("EDAD");
        getContentPane().add(LBLedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));
        getContentPane().add(SPNedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 70, 60, -1));

        LBLgenero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBLgenero.setText("GENERO");
        getContentPane().add(LBLgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 54, -1, -1));

        CMBgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMENINO" }));
        getContentPane().add(CMBgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        BTNgrabar.setText("GRABAR");
        BTNgrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNgrabarActionPerformed(evt);
            }
        });
        getContentPane().add(BTNgrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        LBLtitulo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LBLtitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLtitulo1.setText("AGREGAR");
        getContentPane().add(LBLtitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 460, -1));

        cmbAGENTE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAGENTE2ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbAGENTE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        BTNconsultar.setText("COLSULTAR");
        BTNconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(BTNconsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        BTNborrar.setText("BORRAR");
        BTNborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNborrarActionPerformed(evt);
            }
        });
        getContentPane().add(BTNborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 100, -1));

        BTNactualizar.setText("ACTUALIZAR");
        BTNactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(BTNactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        LBLnombre2.setBackground(new java.awt.Color(51, 51, 255));
        LBLnombre2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        LBLnombre2.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(LBLnombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        LBLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/call-center.jpg"))); // NOI18N
        getContentPane().add(LBLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 560, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        Menu abrir = new Menu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnmenuActionPerformed

    private void TFnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnombreActionPerformed

    private void cmbAGENTE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAGENTE2ActionPerformed
       Conexion cc = new Conexion();
        Connection cn = cc.conexion();
        String sql;
        ResultSet res;
        String id;
        id = (String) cmbAGENTE2.getSelectedItem();
        sql = "SELECT * FROM agente where DOCUMENTO_AGENT='" + id + "'";
        try {

            PreparedStatement psd = cn.prepareStatement(sql);
            res = psd.executeQuery();
           
            if (res.next()) {
               
                LBLnombre2.setText(res.getString("NOMBRE_AGENT"));
            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex);

        }
 
    }//GEN-LAST:event_cmbAGENTE2ActionPerformed

    private void BTNgrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNgrabarActionPerformed
        Conexion cc = new Conexion();
        Connection cn = cc.conexion();
        String nom, id, genero;
        int edad;
        String sql;
        nom = TFnombre.getText();
        id = TFid.getText();
        genero = (String) CMBgenero.getSelectedItem();
        edad = (Integer) SPNedad.getValue();
        sql = "INSERT INTO Agente(DOCUMENTO_AGENT, NOMBRE_AGENT, EDAD_AGENT, GENERO_AGENT) VALUES(?, ?, ?, ?)";
        try {

            PreparedStatement psd = cn.prepareStatement(sql);
            psd.setString(1, id);
            psd.setString(2, nom);
            psd.setInt(3, edad);
            psd.setString(4, genero);
            int n = psd.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "REGISTRO EXITOSO");
                limpiar();
                actualizar();
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }


    }//GEN-LAST:event_BTNgrabarActionPerformed

    private void BTNconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNconsultarActionPerformed
        Conexion cc = new Conexion();
        Connection cn = cc.conexion();
        String sql;
        ResultSet res;
        String id;
        id = (String) cmbAGENTE2.getSelectedItem();
        sql = "SELECT * FROM agente where DOCUMENTO_AGENT='" + id + "'";

        try {

            PreparedStatement psd = cn.prepareStatement(sql);
            res = psd.executeQuery();

           if(res.next()) {
                JOptionPane.showMessageDialog(null, "ID: " + res.getString("DOCUMENTO_AGENT") + "\n" + "NOMBRE: " + res.getString("NOMBRE_AGENT") + "\n" + "EDAD: " + res.getString("EDAD_AGENT") + "\n" + "GENERO: " + res.getString("GENERO_AGENT"));

            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex);

        }

    }//GEN-LAST:event_BTNconsultarActionPerformed

    private void BTNborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNborrarActionPerformed
        Conexion cc = new Conexion();
        Connection cn = cc.conexion();
        String sql;

        String id;
        id = (String) cmbAGENTE2.getSelectedItem();
        sql = "DELETE FROM Estado_agente where DOCUMENTO_AGENT=?";

        try {

            PreparedStatement psd = cn.prepareStatement(sql);
            psd.setInt(1, Integer.parseInt(id));
            int res = psd.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "REGISTRO BORRADO");
            actualizar();
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex);

        }
    }//GEN-LAST:event_BTNborrarActionPerformed

    private void BTNactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNactualizarActionPerformed
       Conexion cc = new Conexion();
        Connection cn = cc.conexion();
       String nom, id, genero;
        int edad;
        String sql;
        nom = TFnombre.getText();
        id = TFid.getText();
        genero = (String) CMBgenero.getSelectedItem();
        edad = (Integer) SPNedad.getValue();
        sql = "update agente set NOMBRE_AGENT=?, EDAD_AGENT=?, GENERO_AGENT=? where DOCUMENTO_AGENT=?";

        try {

            PreparedStatement psd = cn.prepareStatement(sql);
            
            psd.setString(1, nom);
            psd.setInt(2, edad);
            psd.setString(3, genero);
            psd.setString(4, id);
            int res = psd.executeUpdate();
            JOptionPane.showMessageDialog(null, "REGISTRO ACTUALIZADO");
            actualizar();
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex);

        }
    }//GEN-LAST:event_BTNactualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNactualizar;
    private javax.swing.JButton BTNborrar;
    private javax.swing.JButton BTNconsultar;
    private javax.swing.JButton BTNgrabar;
    private javax.swing.JComboBox<String> CMBgenero;
    private javax.swing.JLabel LBLedad;
    private javax.swing.JLabel LBLfondo;
    private javax.swing.JLabel LBLgenero;
    private javax.swing.JLabel LBLid;
    private javax.swing.JLabel LBLnombre;
    private javax.swing.JLabel LBLnombre2;
    private javax.swing.JLabel LBLtitulo1;
    private javax.swing.JLabel LBLtitulo2;
    private javax.swing.JSpinner SPNedad;
    private javax.swing.JTextField TFid;
    private javax.swing.JTextField TFnombre;
    private javax.swing.JButton btnmenu;
    private javax.swing.JComboBox<String> cmbAGENTE2;
    // End of variables declaration//GEN-END:variables
}
